### ISSUE TITLE
panic when resolving Any type with invalid/empty message URL

### ISSUE THREAD

**Issue by mehdijoafshani** [fullstorydev/grpcui#110]
### Context
OS Name: Ubuntu 20.04.2 LTS
OS Type: 64-bit
gRPC Server Technology: Go

### Command
```
	grpcui -import-path ${DAPR_REPO_DIR} \
		-import-path $(PROTO_DIR) \
		-import-path $(GRPC_VALIDATE_DIR) \
		-import-path $(GOOGLE_API_DIR) \
		-proto dapr/proto/runtime/v1/appcallback.proto \
		-proto dapr/proto/runtime/v1/dapr.proto  \
		-proto dapr_message.proto  \
		-proto stream.proto  \
		-proto model.proto  \
		-proto message.proto  \
		-port 7070 \
		-vv \
		-open-browser -plaintext localhost:$(port)
```

### What happens
The API is called twice on each request (instead of once) and for each time the server returns no error.  However, after the second call the grpcui emits the following error:

```
2021/04/05 12:13:12 INFO: 2021/04/05 12:13:12 received request:
POST /invoke/dapr.proto.runtime.v1.AppCallback.OnInvoke HTTP/1.1
Host: 127.0.0.1:7070
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.5
Connection: keep-alive
Content-Length: 226
Content-Type: application/json
Cookie: _grpcui_csrf_token=x-0RD_VLSIMEGg6fdNYroDROzjaWIRgdkVtUpKNIeBw
Origin: http://127.0.0.1:7070
Referer: http://127.0.0.1:7070/
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0
X-Grpcui-Csrf-Token: x-0RD_VLSIMEGg6fdNYroDROzjaWIRgdkVtUpKNIeBw
X-Requested-With: XMLHttpRequest

2021/04/05 12:13:12 INFO: 2021/04/05 12:13:12 sent response:
HTTP/1.1 200 OK
Connection: close

2021/04/05 12:13:12 http: panic serving 127.0.0.1:39988: runtime error: index out of range [0] with length 0
goroutine 37 [running]:
net/http.(*conn).serve.func1(0xc00028cdc0)
        /usr/local/Cellar/go/1.14/libexec/src/net/http/server.go:1772 +0x139
panic(0xbd4fc0, 0xc00026d1a0)
        /usr/local/Cellar/go/1.14/libexec/src/runtime/panic.go:973 +0x396
github.com/jhump/protoreflect/desc.(*FileDescriptor).FindSymbol(0xc0001fd960, 0x0, 0x0, 0x0, 0x83)
        /Users/jh/go/pkg/mod/github.com/jhump/protoreflect@v1.6.1/desc/descriptor.go:192 +0x149
github.com/fullstorydev/grpcurl.(*fileSource).FindSymbol(0xc0000fa640, 0x0, 0x0, 0x0, 0x145eea0, 0x0, 0x0)
        /Users/jh/go/pkg/mod/github.com/fullstorydev/grpcurl@v1.6.0/desc_source.go:185 +0xbb
github.com/fullstorydev/grpcurl.(*anyResolver).Resolve(0xc0005349c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/jh/go/pkg/mod/github.com/fullstorydev/grpcurl@v1.6.0/format.go:250 +0x1e2
github.com/fullstorydev/grpcurl.anyResolverWithFallback.Resolve(0xd4e4c0, 0xc0005349c0, 0x0, 0x0, 0xc0002945b0, 0x197, 0xc0002141b0, 0x83)
        /Users/jh/go/pkg/mod/github.com/fullstorydev/grpcurl@v1.6.0/format.go:287 +0x55
github.com/jhump/protoreflect/dynamic.(*anyResolver).Resolve(0xc00042c2c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x197)
        /Users/jh/go/pkg/mod/github.com/jhump/protoreflect@v1.6.1/dynamic/json.go:1192 +0x47d
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalAny(0xc00047d7d0, 0xc0007486f0, 0xd63380, 0xc00018ff40, 0x0, 0x0, 0xb0, 0x0)
        /Users/jh/go/pkg/mod/github.com/golang/protobuf@v1.3.5/jsonpb/jsonpb.go:422 +0x1ef
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalObject(0xc00047d7d0, 0xc0007486f0, 0xd63380, 0xc00018ff40, 0x0, 0x0, 0x0, 0x0, 0x71345f, 0xc0007486f8)
        /Users/jh/go/pkg/mod/github.com/golang/protobuf@v1.3.5/jsonpb/jsonpb.go:218 +0x13bc
github.com/golang/protobuf/jsonpb.(*Marshaler).Marshal(0xc00047d7d0, 0xd4c800, 0xc00047d800, 0xd63380, 0xc00018ff40, 0xbeb040, 0xbeb000)
        /Users/jh/go/pkg/mod/github.com/golang/protobuf@v1.3.5/jsonpb/jsonpb.go:139 +0x1a6
github.com/golang/protobuf/jsonpb.(*Marshaler).MarshalToString(0xc00047d7d0, 0xd63380, 0xc00018ff40, 0xd63380, 0xc00018ff40, 0x4781e7, 0x478307)
        /Users/jh/go/pkg/mod/github.com/golang/protobuf@v1.3.5/jsonpb/jsonpb.go:145 +0x6e
github.com/jhump/protoreflect/dynamic.marshalKnownFieldValueJSON(0xc00018ff90, 0xc0002c5a80, 0xbeb040, 0xc00018ff40, 0xc00047d7d0, 0x2, 0xc0001db860)
        /Users/jh/go/pkg/mod/github.com/jhump/protoreflect@v1.6.1/dynamic/json.go:450 +0x364
github.com/jhump/protoreflect/dynamic.marshalKnownFieldJSON(0xc00018ff90, 0xc0002c5a80, 0xbeb040, 0xc00018ff40, 0xc00047d7d0, 0x0, 0x7fb9aa624101)
        /Users/jh/go/pkg/mod/github.com/jhump/protoreflect@v1.6.1/dynamic/json.go:311 +0x561
github.com/jhump/protoreflect/dynamic.(*Message).marshalJSON(0xc000099a70, 0xc00018ff90, 0xc00047d7d0, 0xc508e0, 0xc0000fad01)
        /Users/jh/go/pkg/mod/github.com/jhump/protoreflect@v1.6.1/dynamic/json.go:166 +0x258
github.com/jhump/protoreflect/dynamic.(*Message).MarshalJSONPB(0xc000099a70, 0xc00047d710, 0xc000099a70, 0x7fb9837b0d58, 0xc000099a70, 0xc000748b01, 0x46fa87)
        /Users/jh/go/pkg/mod/github.com/jhump/protoreflect@v1.6.1/dynamic/json.go:110 +0x88
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalObject(0xc00047d710, 0xc000749068, 0xd637c0, 0xc000099a70, 0x0, 0x0, 0x0, 0x0, 0xc5829b, 0xc51806)
        /Users/jh/go/pkg/mod/github.com/golang/protobuf@v1.3.5/jsonpb/jsonpb.go:176 +0x2996
github.com/golang/protobuf/jsonpb.(*Marshaler).Marshal(0xc00047d710, 0xd4c800, 0xc00047d7a0, 0xd637c0, 0xc000099a70, 0x1, 0x10)
        /Users/jh/go/pkg/mod/github.com/golang/protobuf@v1.3.5/jsonpb/jsonpb.go:139 +0x1a6
github.com/fullstorydev/grpcui.responseToJSON(0xd62a80, 0xc0000fa640, 0xd637c0, 0xc000099a70, 0x0, 0xffffffffffffffff, 0xc0007491d8, 0xa5fa3b)
        /Users/jh/src/mn/projects/fullstory/go/src/github.com/fullstorydev/grpcui/handlers.go:515 +0x1ea
github.com/fullstorydev/grpcui.(*rpcResult).OnReceiveResponse(0xc0003d4000, 0xd637c0, 0xc000099a70)
        /Users/jh/src/mn/projects/fullstory/go/src/github.com/fullstorydev/grpcui/handlers.go:466 +0x52
github.com/fullstorydev/grpcurl.invokeUnary(0xd662c0, 0xc000278d00, 0xd59140, 0xc0002e2a80, 0xc000423540, 0xc000295040, 0xd683c0, 0xc0003d4000, 0xc0000fa6a0, 0xd637c0, ...)
        /Users/jh/go/pkg/mod/github.com/fullstorydev/grpcurl@v1.6.0/invoke.go:177 +0x44e
github.com/fullstorydev/grpcurl.InvokeRPC(0xd662c0, 0xc000278c40, 0xd62a80, 0xc0000fa640, 0xd59140, 0xc0002e2a80, 0xc0000c850d, 0x2a, 0x145dcb8, 0x0, ...)
        /Users/jh/go/pkg/mod/github.com/fullstorydev/grpcurl@v1.6.0/invoke.go:141 +0x948
github.com/fullstorydev/grpcui.invokeRPC(0xd662c0, 0xc000278c40, 0xc0000c850d, 0x2a, 0xd59140, 0xc0002e2a80, 0xd62a80, 0xc0000fa640, 0x7fb9837b0a20, 0xc000278c00, ...)
        /Users/jh/src/mn/projects/fullstory/go/src/github.com/fullstorydev/grpcui/handlers.go:413 +0x4b9
github.com/fullstorydev/grpcui.RPCInvokeHandler.func1(0xd64580, 0xc000099470, 0xc000108900)
        /Users/jh/src/mn/projects/fullstory/go/src/github.com/fullstorydev/grpcui/handlers.go:68 +0x427
net/http.HandlerFunc.ServeHTTP(0xc0003f9d70, 0xd64580, 0xc000099470, 0xc000108900)
        /usr/local/Cellar/go/1.14/libexec/src/net/http/server.go:2012 +0x44
net/http.StripPrefix.func1(0xd64580, 0xc000099470, 0xc000108700)
        /usr/local/Cellar/go/1.14/libexec/src/net/http/server.go:2051 +0x18a
net/http.HandlerFunc.ServeHTTP(0xc0003f9da0, 0xd64580, 0xc000099470, 0xc000108700)
        /usr/local/Cellar/go/1.14/libexec/src/net/http/server.go:2012 +0x44
github.com/fullstorydev/grpcui/standalone.Handler.func2(0xd64580, 0xc000099470, 0xc000108700)
        /Users/jh/src/mn/projects/fullstory/go/src/github.com/fullstorydev/grpcui/standalone/standalone.go:92 +0x12b
net/http.HandlerFunc.ServeHTTP(0xc0001dab00, 0xd64580, 0xc000099470, 0xc000108700)
        /usr/local/Cellar/go/1.14/libexec/src/net/http/server.go:2012 +0x44
net/http.(*ServeMux).ServeHTTP(0xc0000c18c0, 0xd64580, 0xc000099470, 0xc000108700)
        /usr/local/Cellar/go/1.14/libexec/src/net/http/server.go:2387 +0x1a5
github.com/fullstorydev/grpcui/standalone.Handler.func3(0xd64580, 0xc000099470, 0xc000108700)
        /Users/jh/src/mn/projects/fullstory/go/src/github.com/fullstorydev/grpcui/standalone/standalone.go:113 +0x9b
net/http.HandlerFunc.ServeHTTP(0xc00017e520, 0xd64580, 0xc000099470, 0xc000108700)
        /usr/local/Cellar/go/1.14/libexec/src/net/http/server.go:2012 +0x44
main.main.func4(0xd645c0, 0xc0000fa600, 0xc000108700)
        /Users/jh/src/mn/projects/fullstory/go/src/github.com/fullstorydev/grpcui/cmd/grpcui/grpcui.go:393 +0x14a
net/http.HandlerFunc.ServeHTTP(0xc0001dab20, 0xd64900, 0xc00052c540, 0xc000108700)
        /usr/local/Cellar/go/1.14/libexec/src/net/http/server.go:2012 +0x44
net/http.serverHandler.ServeHTTP(0xc000456700, 0xd64900, 0xc00052c540, 0xc000108700)
        /usr/local/Cellar/go/1.14/libexec/src/net/http/server.go:2807 +0xa3
net/http.(*conn).serve(0xc00028cdc0, 0xd662c0, 0xc000278b80)
        /usr/local/Cellar/go/1.14/libexec/src/net/http/server.go:1895 +0x86c
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.14/libexec/src/net/http/server.go:2933 +0x35c
```

Am I missing anything?
Thanks

**Comment by mehdijoafshani** [comment]
Update:
It was Dapr's retry policy that caused the twice call to the API.
I keep the issue open in case you guys are willing to prevent the panic in such cases.

**Comment by jhump** [comment]
@mehdijoafshani, I think I see the source of the panic. It should definitely return a reasonable error instead of crashing. However, it looks like the error is caused by an `Any` message that has an invalid (possibly empty) type URL. So maybe that 
 info will help you troubleshoot your server.

**Comment by jhump** [comment]
Relevant: https://github.com/jhump/protoreflect/pull/496
