### ISSUE TITLE
Stack trace from go routine

### ISSUE THREAD

**Issue by steverawlins-zebra** [fullstorydev/grpcui#138]
grpcui  -import-path ~/Projects/phoenix-services/libs/protobuf/src/main/proto -import-path ~/Projects/phoenix-services/libs/protobuf/src/  -proto tenant.proto  uat.ssppcoret.zebra.engineering:443
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x13f21b6]

goroutine 1 [running]:
github.com/jhump/protoreflect/desc/protoparse.(*linker).createDescriptorPool(0xc00036ebc0, 0x3ce7ce8, 0x38)
	github.com/jhump/protoreflect@v1.6.1/desc/protoparse/linker.go:138 +0xb36
github.com/jhump/protoreflect/desc/protoparse.(*linker).linkFiles(0xc00036ebc0, 0xc00036ebc0, 0x1, 0x1)
	github.com/jhump/protoreflect@v1.6.1/desc/protoparse/linker.go:32 +0x45
github.com/jhump/protoreflect/desc/protoparse.Parser.ParseFiles(0xc00040e1e0, 0x2, 0x2, 0x0, 0x0, 0x0, 0x1, 0x0, 0xc0002db200, 0x1, ...)
	github.com/jhump/protoreflect@v1.6.1/desc/protoparse/parser.go:212 +0x265
github.com/fullstorydev/grpcurl.DescriptorSourceFromProtoFiles(0xc00040e1e0, 0x2, 0x2, 0xc000406150, 0x1, 0x1, 0x197d3a0, 0xc00040e220, 0x0, 0x0)
	github.com/fullstorydev/grpcurl@v1.7.0/desc_source.go:71 +0x156
main.main()
	github.com/fullstorydev/grpcui/cmd/grpcui/grpcui.go:343 +0x692

**Comment by steverawlins-zebra** [comment]
Thank you.  Right now, I cannot reproduce the error! I was experimenting with two `-import-path`s but now have it down to all our protos in one place.  Maybe that has nothing to do with the stacktrace, but I will close this issue because I cannot reproduce it now.
